export const STRINGS = {
    chatWith: "Chat with",
    typeYourMessage: "Type your message...",
    userMessageAriaLabel: "User message: ",
    godMessageAriaLabel: "God message: ",
    playAudioAriaLabel: "Play audio",
    pauseAudioAriaLabel: "Pause audio",
    sendMessageAriaLabel: "Send message",
    startListeningAriaLabel: "Start listening",
    listeningAriaLabel: "Listening...",
    noGodIdError: "No God ID provided",
    errorFetchingGodName: "Error fetching god name:",
    errorInitializingChat: "Error initializing chat:",
    errorPlayingAudio: "Error playing audio:",
    browserNotSupported: "Your browser does not support speech recognition.",
    errorSendingMessage: "Error sending message: ",
    logoutConfirmation: "Logout Confirmation",
    logoutConfirmationDescription: "Are you sure you want to logout? You'll miss us!",
    fetchDataError: "Error fetching data:",
    fetching: "Fetching...",
    knowMore: "Know More",
    logout: "Logout",
    yesLogout: "Yes, Logout",
    cancel: "Cancel",
    detailedInformation: "Detailed Information",
    close: "Close",
    communityChat: "Community Chat",
    welcomeDashboard: "Welcome to the Spiritual Dashboard",
    errorUpdatingContent: 'Error updating content:',
    loading: 'Loading',
    epicChat: 'Epic Chat',
    epicChatTabs: 'Epic Chat Tabs',
    generatePodcast: 'Generate Spiritual Podcast',
    podcastTabs: 'Podcast Tabs',
    generatePodcastTab: 'Generate Podcast',
    previousPodcastsTab: 'Previous Podcasts',
    podcastListAriaLabel: 'Previous Podcasts',
    stopPodcast: 'Stop',
    listenToPodcast: 'Listen',
    podcast: 'Podcast',
    errorGeneratingPodcast: 'Error generating podcast:',
    loadingTemples: 'Loading temples...',
    loadingDetails: 'Loading details...',
    truncateSuffix: '...',
    enterKey: 'Enter',
    spaceKey: ' ',
    emailRequired: 'Email is required',
    emailInvalid: 'Email address is invalid',
    passwordRequired: 'Password is required',
    login: 'Login',
    emailAddress: 'Email Address',
    password: 'Password',
    or: 'or',
    loginWithGoogle: 'Login with Google',
    noAccountSignUp: "Don't have an account? Sign Up",
    whyThisProduct: 'Why this product and its use cases?',
    emailHelperText: 'email-helper-text',
    passwordHelperText: 'password-helper-text',
    loginForm: 'Login form',
    loginAlert: 'Login alert',
    errorUnknown: 'An unknown error occurred. Please try again.',
    errorUserNotFound: 'No user found with this email. Please sign up first.',
    errorWrongPassword: 'Incorrect password. Please try again.',
    errorInvalidEmail: 'The email address is not valid.',
    errorPopupClosed: 'The Google sign-in popup was closed before completing the sign-in. Please try again.',
    errorMultiplePopup: 'Multiple popup requests. Please try again.',
    errorFetchingConfig: 'Error fetching remote config:',
    errorFetchingQuizQuestions: 'Error fetching quiz questions:',
    quiz: 'Quiz',
    topics: 'Topics',
    failedToGenerateQuiz: 'Failed to generate quiz. Please try again.',
    retry: 'Retry',
    question: 'Question',
    of: 'of',
    quizCompleted: 'Quiz Completed!',
    yourScore: 'Your score',
    passed: 'Passed 😊',
    failed: 'Failed 😢',
    signup: 'Sign Up',
    name: 'Name',
    passwordMinLength: 'Password must be at least 6 characters',
    alreadyHaveAccount: 'Already have an account? Login',
    errorEmailInUse: 'This email is already in use. Please try another one.',
    errorOperationNotAllowed: 'Email/password accounts are not enabled.',
    errorWeakPassword: 'The password is too weak.',
    nameRequired: "Name is required",
    signupWithGoogle: "Sign Up with Google",
    enterYoutubeUrl: 'Please enter a YouTube video URL.',
    validYoutubeUrl: 'Please enter a valid YouTube video URL.',
    summarizeSatsangError: 'Failed to summarize the Satsang video. Please check the URL and try again.',
    summarizeSatsang: 'Summarize Satsang',
    enterYoutubeVideoUrl: 'Enter YouTube Video URL',
    youtubeVideoUrl: 'YouTube Video URL',
    summarizing: 'Summarizing',
    summarize: 'Summarize',
    summary: 'Summary',
    talkToYourGod: 'Talk to Your God',
    initiatingChat: 'Initiating chat...',
    godName: 'God Name',
    godDescription: 'God Description',
    noTempleId: 'No temple ID provided',
    templeNotFound: 'Temple not found',
    errorFetchingTemple: 'Error fetching temple details',
    storiesTab: 'Stories',
    chatTab: 'Chat',
    templeDetailsTabs: 'temple details tabs',
    hanumanChalisaTabs: 'Hanuman Chalisa Tabs',
    understandMeaningsTab: 'Understand Meanings',
    chantAndAnalyzeTab: 'Chant & Analyze',
    goBack: 'Go back',
    chatAbout: 'Chat about',
    errorFetchingWelcomeMessage: 'Error fetching welcome message:',
    playAudio: 'Play audio',
    pauseAudio: 'Pause audio',
    interestingFactsAbout: "Interesting Facts about",
    interestingFactsHeader: "Interesting facts header for",
    interestingFactsContent: "These are interesting facts about the temple.",
    communityRulesTitle: 'Community Rules',
    communityRulesDescription: 'Welcome to the Community Chat! Please adhere to the following rules:',
    ruleNoAbusiveLanguage: 'No abusive language.',
    ruleFocusOnSpiritualTopics: 'Focus on spiritual topics.',
    ruleRespectOpinions: 'Respect everyone\'s opinion.',
    ruleNoSpamming: 'No spamming or advertising.',
    ruleMaintainFriendlyEnvironment: 'Maintain a friendly environment.',
    buttonAgree: 'Agree',
    startChanting: 'Start chanting the Hanuman Chalisa, and we\'ll analyze your performance. Click the button below to begin.',
    analyzing: 'Analyzing...',
    startChantingButton: 'Start Chanting',
    stopChantingButton: 'Stop Chanting',
    analysis: 'Analysis:',
    score: 'Score',
    errorAnalyzingChanting: 'Failed to analyze chanting. Please try again.',
    timestamp: 'Timestamp',
    errorNotification: 'Error notification',
    storyAbout: 'Story about',
    loadingStory: 'Loading story',
    errorMessage: 'Error message',
    storyContent: 'Story content',
    generateNewStory: 'Generate new story',
    audioLoading: 'Audio loading',
    loadingAudio: 'Loading audio',
    listenToStory: 'Listen to story',
    languageToggleTabs: 'Language toggle tabs',
    hindi: 'Hindi',
    english: 'English',
    hanumanChalisa: 'Hanuman Chalisa',
    dailyRecite: 'Many people recite the Hanuman Chalisa daily but struggle to grasp its deeper meanings. With this feature, you can click on any word to understand its significance and save it for future reference.',
    meaningOf: 'Meaning of',
    getExplanation: 'Get Explanation',
    save: 'Save',
    clear: 'Clear',
    hanumanChalisaTitle: 'Hanuman Chalisa',
    hanumanChalisaDescription: 'Delve into the powerful verses of the Hanuman Chalisa.',
    talkToGodTitle: 'Talk To God',
    talkToGodDescription: 'Engage in spiritual conversations and seek divine guidance.',
    generatePodcastTitle: 'Generate Podcast',
    generatePodcastDescription: 'Create and share your spiritual journey through podcasts.',
    communityTitle: 'Community',
    communityDescription: 'Join a community of like-minded spiritual seekers.',
    quizTitle: 'Quiz',
    quizDescription: 'Test and expand your knowledge with our engaging quizzes.',
    summarizeSatsangTitle: 'Summarize Satsang',
    summarizeSatsangDescription: 'Get concise summaries of spiritual talks and satsangs.',
    knowAboutTemplesTitle: 'Know About Temples',
    knowAboutTemplesDescription: 'Explore and learn about various Hindu temples.',
    funFactTitle: 'Fun Fact',
    funFactDescription: 'Discover interesting and lesser-known facts.',
    mythTitle: 'Myth',
    mythDescription: 'Uncover the myths and legends of Hindu culture.',
    epicsAndPuranasTitle: 'Epics and Puranas',
    epicsAndPuranasDescription: 'Dive into the rich stories of Ramayan, Mahabharat, and Puranas.',
};
